[tool.poetry]
name = "adventofcode2024"
description = ""
readme = "README.md"
authors = ["Alexander Sandukovskiy"]
version = "1.0"

[tool.poetry.dependencies]
python = "^3.13.1"
pyright = "^1.1.391"
pytest = "^8.3.4"
